server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:9090/eureka
  instance:
    preferIpAddress: true

spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://db:5432/xotoboil
    driverClassName: org.postgresql.Driver
    username: postgres
    password: admin
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect

flyway:
  user: postgres
  password: admin
  url: jdbc:postgresql://db:5432/xotoboil